### ISSUE TITLE
install extension

### ISSUE THREAD

**Issue by 1191620** [fangq/brain2mesh#14]
hello 
could you help me with installation of this extension on my slicer

**Comment by fangq** [comment]
@1191620, what do you mean by installing this extension on your slicer? were you referring to "[3D slicer](https://www.slicer.org/)" software?

this is a MATLAB/Octave toolbox. unless your environment supports MATLAB/Octave interfaces, I don't think you can install this as an extension (but you can use it separately)

**Comment by 1191620** [comment]
Thanks for your help. I mean how can I run the software in MATLAB. 
Note that: I have just install it and extract the file but I do not know how can run it.

**Comment by 1191620** [comment]
Add that I install Iso2mesh for my goal.

**Comment by fangq** [comment]
the best place to start is to run the built-in examples under [brain2mesh/examples](https://github.com/fangq/brain2mesh/tree/master/examples). install anything that is missing when it complains.
