### ISSUE TITLE
Error due to old `tetgen` binary

### ISSUE THREAD

**Issue by rcassani** [fangq/brain2mesh#15]
Not sure if the issues belongs here or in [iso2mesh](https://github.com/fangq/iso2mesh)

In some places `brain2mesh.m` ([example](https://github.com/fangq/brain2mesh/blob/46f6610de9f5707c3d23a5efefb2f839e40ff7d2/brain2mesh.m#L337)) calls `meshabox.m` which in turns calls `surf2mesh.m` without `method` thus [the default](https://github.com/fangq/iso2mesh/blob/70baeb6833c9a0633fd2fd8803b90cc33b77767e/surf2mesh.m#L34) `'tetgen'` is used. This causes an error as the old binary is used. 

The error is solved by replacing the old binary, `tetgen.mexa64`, with a symbolic link to `tetgen1.5.mexa64`

**Comment by fangq** [comment]
For `meshabox`, I do not believe using the old tetgen (1.4.3) should cause any issue. In fact, tetgen 1.4.3 also works for brain2mesh steps, with the exception that it does not automatically label individual regions. That's the only place where tetgen1.5 is more appropriate. 

what error did you see when calling meshabox?

**Comment by rcassani** [comment]
@fangq, thanks for the quick reply. Indeed the problem was not caused by the old binary, but to the fact that binary did not have execute permissions when downloaded directly from the repo.
