### ISSUE TITLE
how to export model to ABAQUSE

### ISSUE THREAD

**Issue by 1191620** [fangq/brain2mesh#16]
Hello 
Is there any way to export built model by Brain2mesh to Abaqus?

Thank you in advance for your help.

**Comment by fangq** [comment]
@1191620, you can use the `saveabaqus.m` function provided by iso2mesh

https://github.com/fangq/iso2mesh/blob/master/saveabaqus.m

there are some 3rd party functions to convert iso2mesh/brain2mesh mesh data (node, face, elem) to abaqus format, try 

https://groups.google.com/g/iso2mesh-users/c/p0WcKrdBnSs/m/Zzu79pYg_egJ
