### ISSUE TITLE
export Brain2mesh result in ABAQUS

### ISSUE THREAD

**Issue by 1191620** [fangq/brain2mesh#17]
Hello
I have just run Brain2mesh and now I am going to send result to Abaqus , can you help me with it, please.
any suggestion is appreciate highly.

**Comment by fangq** [comment]
you can use `saveabaqus.m` provided in iso2mesh

https://github.com/fangq/iso2mesh/blob/master/saveabaqus.m

**Comment by 1191620** [comment]
Thank you, I have used it, but it exports brain whole model and I am not able to test parts interaction it in ABAQUS. is there any way to export brain's different parts in order to assign various material properties and then assemble them.

**Comment by fangq** [comment]
yes, you can use the last column (labels) of the `elem` element to separate each region. for example

```
[no, el]=removeisolatednode(node, elem(elem(:,5)==1, 1:4));
saveabaqus(no,volface(el),el,'label1');

[no, el]=removeisolatednode(node, elem(elem(:,5)==2, 1:4));
saveabaqus(no,volface(el),el,'label2');
```

calling `removeisolatednode` only keeps the nodes in the specified region, resulting in smaller file sizes.

**Comment by 1191620** [comment]
That is really helpful. thanks.
