### ISSUE TITLE
An error occurs when running SPM_example_wholehead

### ISSUE THREAD

**Issue by xiberJ** [fangq/brain2mesh#19]
Dear developers,
First of all, thank you very much to your team for sharing this tool
I had problems trying to model my brain with brain2mesh. I first installed the required toolkit, I ran check_brain2mesh_dependency, and then I ran SPM_example_wholehead with the following:
![1690185451513](https://github.com/fangq/brain2mesh/assets/122353886/bd1e7076-88ff-477f-a3d6-3148cb9ca12f)

，

In addition, I try to import the generated brain model into comsol for simulation. I also want to know how to control the size of the mesh. In addition, is there a public 3D brain model (step or mesh type file)?
Looking forward to your reply！
best，
jiangyu

**Comment by fangq** [comment]
I can't reproduce the reported issue. the example runs smoothly on my system (Ubuntu Linux, MATLAB 2018).

Please verify that your iso2mesh, brain2mesh and jsonlab are the latest versions.
