### ISSUE TITLE
Input meshes segmented by other tools

### ISSUE THREAD

**Issue by YiChuanJiang** [fangq/brain2mesh#20]
Hi @fangq,

Could you please provide the scripts that accommodate the combination of segmented surface meshes, such as those produced in FreeSurfer and Cat12, as part of the input data?

Thank you in advance.

Bset regards,
Yichuan Jiang

**Comment by fangq** [comment]
@YiChuanJiang, below is a reply I sent to another user with similar request - pleaes download the sample code and install the dependencies and see if it works for you

> hi,
> 
> sorry for the delay. 
> 
> please download this file and give it a try
> 
> https://wazu.coe.neu.edu/~fangq/share/brain2mesh/brain2mesh_freesurfer.zip
> 
> you will need to install the latest iso2mesh, brain2mesh and the following toolbox to read nii file
> 
> https://www.mathworks.com/matlabcentral/fileexchange/8797-tools-for-nifti-and-analyze-image
> 
> upon unzipping the above file, you need to also unzip all .gz files from data/freesurfer/ folder before running the main script
> 
> [node, elem]=freesurfer();
> plotmesh(node, elem, 'x>100');
> 
> did a quick test myself, it works on lInux (Ubuntu 22.04), see screenshot attached. let me know if you have any trouble running it.
> 
> Qianqian
![fsmesh](https://github.com/fangq/brain2mesh/assets/226913/93db2e97-cdca-435e-8759-0f6b20d980a9)

**Comment by YiChuanJiang** [comment]
Hi @fangq,

Thank you for your reply!


Could you please inform me how to generate c1-c6orig.nii.gz in the data folder? 

Do these files correspond to gm, wm, csf, skull, scalp, and air?


Best regards,
Yichuan Jiang

**Comment by fangq** [comment]
those are generated by SPM12
https://www.fil.ion.ucl.ac.uk/spm/software/spm12/
